### ISSUE TITLE
Runs after DKMS modules removed

### ISSUE THREAD

**Issue by norcalli** [bebehei/akulm#1]
dkms modules are named 70-dkms-remove.hook, which seems to have a higher priority than the current hook. Naming it `00-akulm-pre.hook` would remove this problem. Or just mention this potential problem in the README.

**Comment by bebehei** [comment]
@norcalli Thank you for your report. Could you please verify, that the change in the [`fix/issue-1` branch](https://github.com/bebehei/akulm/compare/fix/issue-1) works? I haven't got any systems, which use DKMS modules on Arch.

**Comment by bebehei** [comment]
I just guess, it works. I'll merge it.

**Comment by norcalli** [comment]
I only tested it yesterday, but it does work.
